CryptoProject/main/routes.py
import os.path

from flask import render_template, redirect, Blueprint, url_for
from flask_login import current_user
# import json
import requests

main = Blueprint('main', __name__)


# noinspection PyUnboundLocalVariable,PyProtectedMember
@main.route("/")
@main.route("/home")
def home():
    if not current_user.is_anonymous:
        if current_user._get_current_object().validated:
            return redirect(url_for('users.logged'))
        else:
            return redirect(url_for('users.verification'))

    key = "https://api.binance.com/api/v3/ticker/price?symbol="
    currencies = ["BTCUSDT", "DOGEUSDT", "LTCUSDT", "XRPUSDT", "ETHUSDT"]
    j = 0
    cryptos = dict()
    for _ in currencies:
        url = key + currencies[j]
        data = requests.get(url)
        data = data.json()
        j = j + 1
        if data['symbol'] == "BTCUSDT":
            currency = "Bitcoin"
        elif data['symbol'] == "DOGEUSDT":
            currency = "Dogecoin"
        elif data['symbol'] == "LTCUSDT":
            currency = "Litecoin"
        elif data['symbol'] == "XRPUSDT":
            currency = "Ripple"
        elif data['symbol'] == "ETHUSDT":
            currency = "Ethereum"
        price = float(data['price'])
        round(price, 1)
        cryptos[currency] = price
    return render_template('home.html', title='Home', cryptos=cryptos)

CryptoProject/transactions/routes.py
import struct
import threading
import time
from random import randint
import os.path

import requests
from Crypto.Hash import keccak
from flask import render_template, flash, Blueprint, redirect, url_for
from flask_login import current_user, login_required
from CryptoProject import db
from CryptoProject.models import Transaction, Status, User
from CryptoProject.transactions.forms import TransactionForm, DepositForm, CryptoChangeForm

transactions = Blueprint('transactions', __name__)


@transactions.route("/new_transaction", methods=['GET', 'POST'])
@login_required
def new_transaction():
    if not current_user._get_current_object().validated:
        flash('Your account is not activated for you to be able to make a transaction!', 'danger')
        return redirect(url_for('users.verification'))
    form = TransactionForm()
    if form.validate_on_submit():
        if form.currency.data == 'money':
            helpvar = current_user.money
            helpvar2 = 'money'
        elif form.currency.data == 'bitcoin':
            helpvar = current_user.bitcoin
            helpvar2 = 'bitcoin'
        elif form.currency.data == 'dogecoin':
            helpvar = current_user.dogecoin
            helpvar2 = 'dogecoin'
        elif form.currency.data == 'litecoin':
            helpvar = current_user.litecoin
            helpvar2 = 'litecoin'
        elif form.currency.data == 'ripple':
            helpvar = current_user.ripple
            helpvar2 = 'ripple'
        else:
            helpvar = current_user.ethereum
            helpvar2 = 'ethereum'

        if helpvar >= form.amount.data:
            flash('Your transaction is being processed! After 5 minutes check your Transaction History'
                  ' for information about your transaction', 'success')
            k = keccak.new(digest_bits=256)
            k.update(
                bytes(current_user.email, encoding='utf-8') + bytes(form.email.data, encoding='utf-8') + struct.pack(
                    "<f", form.amount.data) + bytes(randint(1, 99999)))
            transaction_id = k.hexdigest()
            transaction = Transaction(id=transaction_id, sender_id=current_user.email, receiver_id=form.email.data,
                                      amount=form.amount.data, status=Status.IN_PROGRESS.name, currency=helpvar2)
            db.session.add(transaction)
            db.session.commit()
            sender = current_user.email
            try:
                threading.Thread(target=transaction_thread, args=(form.email.data, form.amount.data,
                                                                  transaction_id, sender, helpvar2)).start()
            finally:
                return redirect(url_for('users.logged'))
        else:
            k = keccak.new(digest_bits=256)
            k.update(
                bytes(current_user.email, encoding='utf-8') + bytes(form.email.data, encoding='utf-8') + struct.pack(
                    "<f", form.amount.data) + bytes(randint(1, 99999)))
            transaction = Transaction(id=k.hexdigest(), sender_id=current_user.email, receiver_id=form.email.data,
                                      amount=form.amount.data, status=Status.DENIED.name, currency=helpvar2)
            db.session.add(transaction)
            db.session.commit()
            flash('Insufficient funds!', 'danger')
    return render_template('transaction.html', form=form, verified=True)


@transactions.route("/deposit", methods=['GET', 'POST'])
@login_required
def deposit():
    if not current_user._get_current_object().validated:
        flash('Your account is not activated', 'danger')
        return redirect(url_for('users.verification'))
    form = DepositForm()
    if form.validate_on_submit():
        try:
            current_user.money = current_user.money + form.amount.data
            db.session.commit()
            flash('Your transaction has been processed.'
                  f' The amount of {form.amount.data} has been added to your personal account', 'success')
        except:
            flash('Your transaction has been denied', 'danger')
    return render_template('deposit.html', form=form, verified=True)


@transactions.route("/convert", methods=['GET', 'POST'])
@login_required
def convert():
    if not current_user._get_current_object().validated:
        flash('Your account is not activated', 'danger')
        return redirect(url_for('users.verification'))
    form = CryptoChangeForm()
    cryptos = get_cryptos()
    cryptos['money'] = 1
    x = 0
    new_value = 0
    if form.validate_on_submit():
        if form.first_currency.data == form.second_currency.data:
            flash('You cannot convert the same currency!', 'danger')
        else:
            if form.first_currency.data == 'money':
                helpvar = current_user.money
                if helpvar >= form.amount.data:
                    new_value = cryptos[form.first_currency.data] / cryptos[form.second_currency.data] \
                                * form.amount.data
                    current_user.money = current_user.money - form.amount.data
                else:
                    flash('Insufficient funds!', 'danger')
                    x += 1
            elif form.first_currency.data == 'bitcoin':
                helpvar = current_user.bitcoin
                if helpvar >= form.amount.data:
                    new_value = cryptos[form.first_currency.data] / cryptos[form.second_currency.data] \
                                * form.amount.data
                    current_user.bitcoin = current_user.bitcoin - form.amount.data
                else:
                    flash('Insufficient funds!', 'danger')
                    x += 1
            elif form.first_currency.data == 'dogecoin':
                helpvar = current_user.dogecoin
                if helpvar >= form.amount.data:
                    new_value = cryptos[form.first_currency.data] / cryptos[form.second_currency.data] \
                                * form.amount.data
                    current_user.dogecoin = current_user.dogecoin - form.amount.data
                else:
                    flash('Insufficient funds!', 'danger')
                    x += 1
            elif form.first_currency.data == 'litecoin':
                helpvar = current_user.litecoin
                if helpvar >= form.amount.data:
                    new_value = cryptos[form.first_currency.data] / cryptos[form.second_currency.data] \
                                * form.amount.data
                    current_user.litecoin = current_user.litecoin - form.amount.data
                else:
                    flash('Insufficient funds!', 'danger')
                    x += 1
            elif form.first_currency.data == 'ripple':
                helpvar = current_user.ripple
                if helpvar >= form.amount.data:
                    new_value = cryptos[form.first_currency.data] / cryptos[form.second_currency.data] \
                                * form.amount.data
                    current_user.ripple = current_user.ripple - form.amount.data
                else:
                    flash('Insufficient funds!', 'danger')
                    x += 1
            else:
                helpvar = current_user.ethereum
                if helpvar >= form.amount.data:
                    new_value = cryptos[form.first_currency.data] / cryptos[form.second_currency.data] \
                                * form.amount.data
                    current_user.ethereum = current_user.ethereum - form.amount.data
                else:
                    flash('Insufficient funds!', 'danger')
                    x += 1
            if form.second_currency.data == 'money':
                current_user.money = current_user.money + new_value
            elif form.second_currency.data == 'bitcoin':
                current_user.bitcoin = current_user.bitcoin + new_value
            elif form.second_currency.data == 'dogecoin':
                current_user.dogecoin = current_user.dogecoin + new_value
            elif form.second_currency.data == 'litecoin':
                current_user.litecoin = current_user.litecoin + new_value
            elif form.second_currency.data == 'ripple':
                current_user.ripple = current_user.ripple + new_value
            elif form.second_currency.data == 'ethereum':
                current_user.ethereum = current_user.ethereum + new_value
            db.session.commit()
            if x == 0:
                flash('You successfully converted!', 'success')
    return render_template('convert.html', form=form, verified=True, cryptos=get_cryptos())


@transactions.route("/history")
@login_required
def transaction_history():
    if not current_user._get_current_object().validated:
        flash('Your account is not activated', 'danger')
        return redirect(url_for('users.verification'))
    historySend = Transaction.query.filter_by(sender_id=current_user.email).all()
    historyRecv = Transaction.query.filter_by(receiver_id=current_user.email).all()
    for h in historyRecv:
        if h.status == 'IN_PROGRESS' or h.status == 'DENIED':
            historyRecv.remove(h)
    return render_template('history.html', historySend=historySend, historyRecv=historyRecv, verified=True)


def transaction_thread(email, amount, transaction_id, sender, helpvar):
    from run import app
    time.sleep(10)
    try:
        with app.app_context():
            user = User.query.filter_by(email=email).first()
            i_did_it = User.query.filter_by(email=sender).first()
            transaction_done = Transaction.query.filter_by(id=transaction_id).first()
            if helpvar == 'money':
                if i_did_it.money - amount < 0:
                    transaction_done.status = Status.DENIED.name
                    transaction_done.currency = 'dollar'
                else:
                    user.money = user.money + amount

CryptoProject/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from CryptoProject import db, bcrypt
from CryptoProject.models import User
from CryptoProject.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, VerificationForm)


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password, name=form.name.data, surname=form.surname.data, address=form.address.data,
                    city=form.city.data, state=form.state.data, cellphone=form.cellphone.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user._get_current_object().validated:
            return redirect(url_for('users.logged'))
        else:
            return redirect(url_for('users.verification'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.verification'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    if current_user._get_current_object().validated:
        verified = True
        form = UpdateAccountForm()
        if form.validate_on_submit():
            current_user.username = form.username.data
            current_user.email = form.email.data
            current_user.name = form.name.data
            current_user.surname = form.surname.data
            current_user.address = form.address.data
            current_user.city = form.city.data
            current_user.state = form.state.data
            current_user.cellphone = form.cellphone.data
            db.session.commit()
            flash('Your account has been updated!', 'success')
            return redirect(url_for('users.account'))
        elif request.method == 'GET':
            form.username.data = current_user.username
            form.email.data = current_user.email
            form.name.data = current_user.name
            form.surname.data = current_user.surname
            form.address.data = current_user.address
            form.city.data = current_user.city
            form.state.data = current_user.state
            form.cellphone.data = current_user.cellphone
        return render_template('account.html', title='Account', form=form, verified=verified)
    else:
        # verified = False
        flash("Your account is not activated!", "danger")
        return redirect(url_for('users.verification'))


@users.route("/verification", methods=['GET', 'POST'])
@login_required
def verification():
    if current_user._get_current_object().validated:
        return redirect(url_for('main.home'))
    else:
        form = VerificationForm()
        verified = False
        if form.validate_on_submit():
            if form.number.data == "4242424242424242" or form.number.data == "4242 4242 4242 4242" and \
                    form.name.data == current_user.name and form.expires.data == "02/23" and form.ccv.data == "123":
                current_user.validated = True
                db.session.commit()
                return redirect(url_for('users.logged'))
            else:
                flash('Wrong credentials! Try again!', 'danger')
        else:
            return render_template('verification.html', title='Verification', form=form, verified=verified)


@users.route("/logged", methods=['GET', 'POST'])
@login_required
def logged():
    if not current_user._get_current_object().validated:
        return redirect(url_for('users.verification'))
    else:
        verified = True
        return render_template('logged.html', verified=verified)


@users.route("/balance")
@login_required
def balance():
    if not current_user._get_current_object().validated:
        return redirect(url_for('users.verification'))
    else:
        current_money = current_user.money
        current_bitcoin = current_user.bitcoin
        current_dogecoin = current_user.dogecoin
        current_litecoin = current_user.litecoin
        current_ripple = current_user.ripple
        current_ethereum = current_user.ethereum
        return render_template('balance.html', current_money=current_money, current_bitcoin=current_bitcoin,
                               current_dogecoin=current_dogecoin, current_litecoin=current_litecoin,
                               current_ripple=current_ripple, current_ethereum=current_ethereum, verified=True)

CryptoProject/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.surname.label(class="form-control-label") }}
                    {% if form.surname.errors %}
                        {{ form.surname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.surname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.surname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.address.label(class="form-control-label") }}
                    {% if form.address.errors %}
                        {{ form.address(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.address(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.city.label(class="form-control-label") }}
                    {% if form.city.errors %}
                        {{ form.city(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.city.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.city(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.state.label(class="form-control-label") }}
                    {% if form.state.errors %}
                        {{ form.state(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.state.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.state(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                 <div class="form-group">
                    {{ form.cellphone.label(class="form-control-label") }}
                    {% if form.cellphone.errors %}
                        {{ form.cellphone(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.cellphone.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.cellphone(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Crypto Exchange 2023®
        </small>
    </div>
{% endblock content %}

CryptoProject/templates/balance.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
            <fieldset>
                <legend class="border-bottom mb-4"><h1>Your Balance</h1></legend>
                <div>
                    <h3>Dollars: {{ current_money }} $</h3>
                    <p></p>
                    <h3>Bitcoin: {{ current_bitcoin }} BTC</h3>
                    <p></p>
                    <h3>Dogecoin: {{ current_dogecoin }} DOGE</h3>
                    <p></p>
                    <h3>Litecoin: {{ current_litecoin }} LTC</h3>
                    <p></p>
                    <h3>Ripple: {{ current_ripple }} RIPPLE</h3>
                    <p></p>
                    <h3>Ethereum: {{ current_ethereum }} ETH</h3>
                </div>
            </fieldset>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Crypto Exchange 2023®
        </small>
    </div>
{% endblock content %}

CryptoProject/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Crypto Exchange - {{ title }}</title>
    {% else %}
        <title>Crypto Exchange</title>
    {% endif %}

</head>
<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Crypto Exchange</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
          {% if verified == True %}
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Sidebar</h3>
                    <p class='text-muted'>
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">
                                <a href="{{ url_for('transactions.new_transaction')}}">New Transaction</a></li>
                            <li class="list-group-item list-group-item-light">
                                <a href="{{ url_for('transactions.transaction_history')}}">Transactions History</a></li>
                            <li class="list-group-item list-group-item-light">
                                <a href="{{ url_for('users.balance')}}">Account Balance</a></li>
                            <li class="list-group-item list-group-item-light">
                                <a href="{{ url_for('transactions.deposit')}}">Deposit To Online Account</a></li>
                            <li class="list-group-item list-group-item-light">
                                <a href="{{ url_for('transactions.convert')}}">Crypto Change</a></li>
                        </ul>
                    </p>
                </div>
            </div>
          {% else %}
            <div>
            </div>
          {% endif %}



      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

CryptoProject/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}